# rust-toolchain.toml

[toolchain]
channel = "stable"
# You can specify a precise version if needed, e.g., "1.65.0"
# channel = "1.65.0"
components = [
    "rustfmt",
    "clippy",
    "rust-src",       # Required for certain IDE integrations
    "rust-analyzer",  # Optional: for enhanced IDE support
]
targets = [
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown",  # Example for WebAssembly targets
]

# Optional: Override default profiles
[profile.dev]
debug = true
split-debuginfo = "packed"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "packed"
