aws:
    config: ENC[AES256_GCM,data:5nHiOHPdvv/ncPB5IErwfef0tkHP5sTNCo7cT75tqZQF72zZ+HC50P4Ydr33Lubq4ZYl/kuy17Ue5koFTmhw7d4W+19DeeD3HZYkcCWpBuLmttGMGTSzvlrfIbB+P9M5ixFFC24RVzFLnscU4AMZ7ZcXVZMIqdB/gtE5q0Z2LmibsDoyZftAdVnQvonyNpryM3/uXHJXyr+8Cl/TPhSCyq90mgIFIFhdo1Wo8dF4IIvhrxxgnM9xIH/1hPb/HKZmnqRueMpRVrZXIeBXzoG+AvnhstwFfd68fgvpoXPnWBY42/6q8vcDMIix8CZO2o/wpRcnpJwTa3Dqj74IwQTQE45ZNvxI4wzSS+YxS925xOLdYuo5oCa1UGwHbHUevJoLcLytXoXxNOXp89yITO2nrgZkDlLPT461Bp7wbGtuaueMF6kmp42aBxM/cmd7eXvjNTlnWEt6ANCaTY9w/ctyEtjj4KysRDUEa+wi8zCmSUu4NgxL5e2J4BsiODkGvt/Zf+30MNR1UpPpr7taDs26DWuefWe0SXgl4rCJuYV9F56a72NKeiZuESWpFhRFcP/UzHsHreAAfYdoWUnxq6U69bYL4ExnynH7R/B4xxsP+vC+aPsEiaUvNxQAWI/WocYla/GNg3glhQ7cvoO+JDyFj6/jsAoLUMwpuHIfNBffPp5soFyY9+u4se+prx1QgAJgIzUfNOt8RpA2U7UVw/Lyn18gkApPveav2Wk3K6e0qfP+y6eB+jfbeTFB7Dxqy1G414g9Ii7lZov2k1ZQ/ZZaE/oAn5gCPl3nuBhU0kScw38o0yrGb6v92dNTs3xkPiDAGzg8SVKr4vNWglDWjrBTykMhhC6MSvPzetolf89sgMY+cqpHqSH3oSJ2aw0HpGITJ9OjCPYuTxz989DJ0FnVdPby90na5P3IoSz3D9rWpBEm+ajwfVQpatBsgQIXxrSbtq7jvHf92uilbpkZR9SVaDaJAgOcBVDtcv5yA49Gj6G4Sx68wesx1xzCb74U1Pwt/5rtbucHmXAVht+PLqo+eZZrmgJiLocpeD8pjHOFw1waO3g8BY5CH7UV21ZkIE3MK6x5bH+XlQ/kBxXBNm2yHhuDK8SbJknHqMeR/7zRcLsFAo014/JiVK0It8TAfQpNIy5h2BeRyhRSjTf29idaNHUfaA0c1if+5/Ot6j1e6vcwZv6vWSOzcTDA7ybbcwmkYAUkOj5trQsYim5yDVCSdOsb9VCOPqUstwQyaZ3uHXFCXRdP1ezjpNz20Te2O0xArn3jyGICrrlM2YJHkW01LfRnwfkMGi4Fb//FAOwyt2Dm2/w7tk2tSZQF8vaLPCnadpL6iRlUTklVdT3lrqLis/o/6euZugGwGfuBGgQALOPrD9KVBZLQDt02GWFghYREYGkWjJFa9ewIDg+0IiSK7Uur21lxMlXJ69EKGhdbHXyIGZf/vbr//04ZJLk5hphL4Uje5kDZ5UpUKxzooOGXBoJqJEwiCG0C1naAfMVdUIGn2Z1kacNx0oxdpjFMjF5ynxQ51KYN4JPkQiTwVuvNkTPbRp5XO4FyPGfPHlrF3hyF0OAYcLEiNgAj8UnPZjU6Y+sdbU5eBo37xGRjqy2p7B2OUEei4COou9Hx1GDD93yrmvyLKxuybwt7PrEwovSaEPiuXpZo/Y+Jk6hOqVUx829M59rPQrjETPGDhLa8KnMt/t6IX5cMhyZi9m4MSWZvVX+V//TEnL3xFNLz5r9Cx/9RKMcqsBN+Ja7PhaadhxwK9WIcj6R4ewCVQDfgsc2GSk9BvA0GS6zFvEWjLFMlmZ+7GlcOeSjqPPwZqHqRfCYkziBJ93zG8ql+lLWHRM2nnuE64lh43RssOBLnpZvqyEz6bH5M5wXoFVHjod8looaPe3faXai4zNhCmbz7XNqHWIyN8FhVn4zltFvZINccaMp1RG27C2PdC3pA9BQJiOvFZBifxvLnkyLXOY/3SOEHzBO9QMIfVncR47Qa3WDKgLhg2D/mtaqwLuNUcOaAsjrqGYHoVQGO70N05agCQkKSRAr+MhDu52o+GZ4RrDwjOW6tSdHeeKQtWTEaf66o6OTmh7FBKPGIk/79KMHbJDqJXh89ETcylJoiKVB0AymhjqFt29a7HvNMoDmSkl40u8mk3NwccR/xvdS3azQ5JW/CGrZ+gfwwE1EjLJVbs4C39qHDEHzbAC/5FGwf3KygIzUFGpTfZ2toK1F6RoMkyGBTJAA=,iv:bO/zAX8/ueP8C8pgRX8ZpVtzRULX4p8XhSFyOXIvUuc=,tag:Kjf2AkVU7MX8vBKGYOm/iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-03T04:02:27Z"
    mac: ENC[AES256_GCM,data:Fo6hPy1YjGN4HvuRUBKrYGod4n8InNpH6D9BL9UmJVsEZo34GqTLcrh6h3ldjjBV2pjkrzHIW757QiZqLhgY1JuF+oJvvuIljCxoc7FPC/R/CS5hR2RykZjgKgXaSHTFkIiPPrAOK8sJ4iKZgR43SQ13KKLR20rSRM+nWL7r0UY=,iv:rtPB29db/2rWtBX0FgcGC8LNy790Pucn3XgyfEAWXLk=,tag:I/la1K5urxvA0ZAS1xKnew==,type:str]
    pgp:
        - created_at: "2024-10-03T04:01:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4YbIW5pPlRhAQ//cGWvn5NSzoNPi+xa7hWFlFyZn+x8nRnZkw6kSp1PrSBx
            nmXxOL5rgCW5taMzi1vjYhdLdckJbonyODSOwrUSFbnSiu6xY0U2N1ZCtpMTfSxa
            VWSpXlQgt6jMOBrnTdnom5GLoC0nWoCE+KD9pPkq3z0tMMe7zyMxPpu1lXN37uAy
            wASMbtVJcNlRT3Uydg0n/kbZVnNYsXsatJcU9XldnBaOH5bxgTxtBRVEmt+pWZRR
            a0cwgUFzlTZiEcRXOgyEopmKxHbJM1T8L+ZeNH2FU6AwENVaF68gvL2b8idKf61M
            Jjw6SsNPj+hw12VnX0wExp7MNl+XiBlcJgvdAyl8SVylcpv5a3T+I8O55ZV1UGxy
            1MLwCQJ7cEEUg4E8xcLviKsntsvG5NI884lWPsa1yi2onEMDk8ASiTB78fsSFO5Y
            rqoa3S/RPAndT98sVJW+n7YciR9FsLtxJUp2mWsn+0VPjLg19RX0ojNEtaDxeXko
            zf8TeyzLxvkTqLxEECMadnfFTA4dOzgnyrLh1UCqHOA5VSqe5ez/U+Yp3IVnQaqx
            v2DacLhx0S/+9PqCfWnhxLnhE/EG+0nS25/vSW8Bphn0v+jm4HcvwP/M+vtP2Lgs
            WqtZ1OAvG8T+5giUYe0KhdTyD1b8yGZfKrUK9W+6g+OOHFiY8hYdTK5Sxr1Bd73S
            XgGYbmqJPAu52+tUg/loIvY2hvUwknRygSs5x43mWiHuJqfqWXKUlNEkoiMbxWY7
            oRCjtzndwnMyxUL+FhOd8K01h9haphdG6Pi86UOt2AAFNtLjI++apywFFZtwXKw=
            =m5oA
            -----END PGP MESSAGE-----
          fp: 6F7E7A535A92FF75B4492B233B2E5A1B7358B60A
    unencrypted_suffix: _unencrypted
    version: 3.9.0
